/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import control.control_transaksiPelanggan;
import control.Pembelian;
import control.koneksi;
import control.laporan;
import control.utama;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;


/**
 *
 * @author ASUS
 */
public class TransaksiPelanggan extends javax.swing.JFrame {
    control_transaksiPelanggan ct;
    laporan lp;
    koneksi db;
    utama ut;
    

    public String kode_barang;
    public String nama_barang;
    public static int qty;
    public static int harga;
    public static int stok;
    public int total;
   
    /**
     * Creates new form Transaksi
     */
    public TransaksiPelanggan() {
        initComponents();
        Dimension dmax = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMaximumSize(dmax);
        this.setSize(dmax.width,dmax.height);
        this.setLocationRelativeTo(null);
   
        db = new koneksi();
        ct = new control_transaksiPelanggan();
        lp = new laporan();
        ut = new utama();
        tbPengeluaran.setModel(ct.model);
        ct.tampilPengeluaran("", "", 0, 0, 0);
        ct.noFak();
        setTanggal();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPengeluaran = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txkode = new javax.swing.JTextField();
        txnama = new javax.swing.JTextField();
        txqty = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txpelanggan = new javax.swing.JTextField();
        txNofak = new javax.swing.JTextField();
        txtotal2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txGrandTotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txDiskon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txKembali = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txidPelanggan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tanggall = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        tampilTTL = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txKasir = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tbPengeluaran.setBackground(new java.awt.Color(242, 170, 76));
        tbPengeluaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPengeluaran);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("ITEM BARANG"));

        txkode.setEditable(false);

        txnama.setEditable(false);
        txnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnamaActionPerformed(evt);
            }
        });

        txqty.setEditable(false);
        txqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txqtyKeyTyped(evt);
            }
        });

        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_40px.png"))); // NOI18N
        btnCari.setEnabled(false);
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel1.setText("KODE BARANG");

        jLabel2.setText("NAMA BARANG");

        jLabel3.setText("QTY");

        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_35px.png"))); // NOI18N
        btncancel.setText("CANCEL");
        btncancel.setEnabled(false);
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_new_document_40px.png"))); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_35px.png"))); // NOI18N
        btnSimpan.setText("SIMPAN");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_40px.png"))); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.setEnabled(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txkode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txqty, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancel)))
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txqty, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txkode)
                            .addComponent(txnama))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSimpan)
                                .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PEMBAYARAN"));

        txpelanggan.setEditable(false);
        txpelanggan.setText("UMUM");

        txNofak.setEditable(false);
        txNofak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNofakActionPerformed(evt);
            }
        });

        txtotal2.setEditable(false);

        jLabel4.setText("No. Faktur");

        jLabel5.setText("Nama Pelanggan");

        jLabel6.setText("Sub Total");

        txGrandTotal.setEditable(false);

        jLabel7.setText("Diskon (%)");

        txDiskon.setEditable(false);
        txDiskon.setText("0");
        txDiskon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txDiskonCaretUpdate(evt);
            }
        });

        jLabel8.setText("Total Belanja");

        txBayar.setEditable(false);
        txBayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txBayarCaretUpdate(evt);
            }
        });

        jLabel9.setText("Bayar");

        txKembali.setEnabled(false);

        jLabel10.setText("Kembali");

        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_print_70px.png"))); // NOI18N
        btnCetak.setEnabled(false);
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("CETAK NOTA");

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_process_70px.png"))); // NOI18N
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SIMPAN");

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_reset_70px.png"))); // NOI18N
        btnReset.setEnabled(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("RESET");

        txidPelanggan.setEditable(false);
        txidPelanggan.setText("P0001");
        txidPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txidPelangganActionPerformed(evt);
            }
        });

        jLabel17.setText("ID Pelanggan");

        jLabel20.setFont(new java.awt.Font("Dialog", 3, 10)); // NOI18N
        jLabel20.setText("*Diskon hanya dapat diberikan melalui menu transaksi kasir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(txidPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txNofak)
                            .addComponent(jLabel17)
                            .addComponent(txtotal2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(txBayar))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(txGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 19, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(txNofak, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txidPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, 0)
                        .addComponent(txtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, 0)
                        .addComponent(txBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCetak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset))
                .addGap(30, 30, 30))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 170, 76));
        jLabel13.setText("HIRO TOY STORE");

        tanggall.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tanggall.setForeground(new java.awt.Color(236, 77, 55));
        tanggall.setText("2020-03-28");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 77, 55));
        jLabel15.setText("Tanggal :");

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "TOTAL BELANJA PELANGGAN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel1.setkGradientFocus(250);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 102, 102));

        tampilTTL.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        tampilTTL.setForeground(new java.awt.Color(242, 170, 76));
        tampilTTL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tampilTTL.setText("0");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilTTL, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilTTL, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 77, 55));
        jLabel16.setText("Kasir :");

        txKasir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txKasir.setForeground(new java.awt.Color(236, 77, 55));
        txKasir.setText("0000");
        txKasir.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));

        jLabel18.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel18.setText("Menu Transaksi Pelanggan");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(242, 170, 76), 2, true));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/514b2f3f5dfc27ef10146c7d1e990000.png"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(242, 170, 76), new java.awt.Color(0, 0, 0), java.awt.Color.gray, new java.awt.Color(242, 170, 76)));
        jLabel19.setMaximumSize(new java.awt.Dimension(75, 75));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_to_70px.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setText("KEMBALI KE MENU UTAMA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(tanggall)
                                .addGap(43, 43, 43)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txKasir))
                            .addComponent(jLabel13))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(jLabel21))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggall)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(txKasir))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        frmCariBarangPelanggan frm = new frmCariBarangPelanggan(null, true,"Transaksi");
        frm.setTitle("PILIH BARANG");
        frm.setVisible(true);
      
       
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        btnCari.setEnabled(true);
        btnNew.setEnabled(false);
        btncancel.setEnabled(true);
       

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        kode_barang = txkode.getText();
        nama_barang = txnama.getText();
        qty = Integer.parseInt(txqty.getText());
        total = harga*qty;
        int total1 = 0;
        int subTotal = 0;
        int hargajual;
        int qty1;
        int total2 = 0;
        
         if(txqty.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "ISI QTY TERLEBIH DAHULU");
        }else if(qty>=stok){
             JOptionPane.showMessageDialog(this, "STOK TIDAK MENCUKUPI");
        }else{
            ct.tampilPengeluaran(kode_barang, nama_barang, harga, qty, total);
            txkode.setText("");
            txnama.setText("");
            txqty.setText("");
            for(int n =0;n<tbPengeluaran.getRowCount();n++){
              hargajual = (int) tbPengeluaran.getValueAt(n, 2);
                qty1 = (int) tbPengeluaran.getValueAt(n, 3);
                 total1 = hargajual*qty;
                  total2 = (int) tbPengeluaran.getValueAt(n, 4);
                  
                  subTotal += total2;
                
            }
            tampilTTL.setText(Integer.toString(subTotal));
            txtotal2.setText(Integer.toString(subTotal));
            txDiskon.setText("0");
            
        }

        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
        btnSimpan.setEnabled(false);
        btncancel.setEnabled(false);
        txDiskon.setEditable(false);
        txBayar.setEditable(true);
        txqty.setEditable(false);
        txqty.setText("");
        txBayar.requestFocus();
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txDiskonCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txDiskonCaretUpdate
        // TODO add your handling code here:
        if(txDiskon.getText().length()>0){
            int subtotal = Integer.parseInt(txtotal2.getText());
            int diskon = Integer.parseInt(txDiskon.getText());
            int ndiskon = subtotal*diskon/100;
            int total = subtotal - ndiskon;
            txGrandTotal.setText(Integer.toString(total));
           
        }
    }//GEN-LAST:event_txDiskonCaretUpdate

    private void txBayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txBayarCaretUpdate
        // TODO add your handling code here:
        if(txBayar.getText().length()>0){
            int bayar = Integer.parseInt(txBayar.getText());
            int total = bayar-Integer.parseInt(txGrandTotal.getText());
            txKembali.setText(Integer.toString(total));
            
            btnSave.setEnabled(true);
            btnReset.setEnabled(true);
          
            
        }
    }//GEN-LAST:event_txBayarCaretUpdate

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String nofak = txNofak.getText();
        String kasir = txKasir.getText();
        String id_pelanggan = txidPelanggan.getText();
        String pelanggan = txpelanggan.getText();
       int total = Integer.parseInt(txGrandTotal.getText());
       int diskon = Integer.parseInt(txDiskon.getText());
       int bayar = Integer.parseInt(txBayar.getText());
       int kembali = Integer.parseInt(txKembali.getText());
      

       String tanggal = tanggall.getText();
       if(bayar<total){
           JOptionPane.showMessageDialog(rootPane, "PEMBAYARAN KURANG");
       }else{
            for(int n = 0;n<tbPengeluaran.getRowCount();n++){
            try {
                String kode_barang = (String) tbPengeluaran.getValueAt(n, 0);
                String nama_barang = (String) tbPengeluaran.getValueAt(n, 1);
                int harga = (int) tbPengeluaran.getValueAt(n, 2);
                int qty = (int) tbPengeluaran.getValueAt(n, 3);
                int totall = (int) tbPengeluaran.getValueAt(n, 4);
                db.setKoneksi();
                String sqli = "SELECT stok from masterBarang where kode_barang = '"+kode_barang+"'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rs = st.executeQuery(sqli);
                while(rs.next()){
                    int stok = rs.getInt("stok");
                    int sisa = stok - qty;
                    ct.updateStok(sisa, kode_barang);
                    
                }
                try {
                    ct.insertBarang(nofak, kode_barang, nama_barang, harga, qty, totall);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPelanggan.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException ex) {
                Logger.getLogger(TransaksiPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
       
        
        try {
            Pembelian.bayar = bayar;
            Pembelian.diskon = diskon;
            Pembelian.kembali = kembali;
            Pembelian.total = total;
            Pembelian.tanggal = tanggal;
            
            ct.simpanPenjualan(nofak,kasir,id_pelanggan, pelanggan, diskon,total,bayar,kembali,tanggal);
            JOptionPane.showMessageDialog(rootPane, "DATA BERHASIL DI SIMPAN");
        } catch (SQLException ex) {
            Logger.getLogger(TransaksiPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        } 
         btnSave.setEnabled(false);
         btnCetak.setEnabled(true);
         btnNew.setEnabled(false);
       }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        btncancel.setEnabled(false);
        btnSimpan.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
        btnhapus.setEnabled(false);
        txqty.setEditable(false);
        txqty.setText("");
        tbPengeluaran.clearSelection();
    }//GEN-LAST:event_btncancelActionPerformed

    private void tbPengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPengeluaranMouseClicked
        // TODO add your handling code here:
        btnhapus.setEnabled(true);
        btnSimpan.setEnabled(false);
        btncancel.setEnabled(true);
    }//GEN-LAST:event_tbPengeluaranMouseClicked

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    int row = tbPengeluaran.getSelectedRow();
        ct.model.removeRow(row);
        btnhapus.setEnabled(false);
        btncancel.setEnabled(false);
        btnNew.setEnabled(true);
        btnCari.setEnabled(false);
        int subTotal = 0;
          for(int n =0;n<tbPengeluaran.getRowCount();n++){
              int hargajual = (int) tbPengeluaran.getValueAt(n, 2);
                int  qty1 = (int) tbPengeluaran.getValueAt(n, 3);
                int  total1 = hargajual*qty;
                int total2 = (int) tbPengeluaran.getValueAt(n, 4);
                  
                subTotal += total2;
                
            }
            tampilTTL.setText(Integer.toString(subTotal));
            txtotal2.setText(Integer.toString(subTotal));
            txDiskon.setText("0");
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txNofakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNofakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNofakActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        Laporanfix frm = new Laporanfix(this, rootPaneCheckingEnabled);
        frm.setTitle("");

        frm.setVisible(true);
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ct.model.removeRow(0);
        tampilTTL.setText("0");
        tbPengeluaran.removeAll();
        ct.noFak();
        txpelanggan.setText("UMUM");
        txDiskon.setText("0");
        txtotal2.setText("");
        txGrandTotal.setText("");
        txBayar.setText("");
        txKembali.setText("");
        txBayar.setEditable(false);
        txDiskon.setEditable(false);
        ct.model.setRowCount(0);
        btnCetak.setEnabled(false);
        btnReset.setEnabled(false);
        //btnCariPlg.setEnabled(false);
        btnSave.setEnabled(false);
        btnCetak.setEnabled(false);
        btnNew.setEnabled(true);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       frmAwal frm = new frmAwal();
       dispose();
       frm.setVisible(true);   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         ut.tampilCountTrx();
        
    }//GEN-LAST:event_formWindowClosing

    private void txqtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txqtyKeyTyped
        // TODO add your handling code here:
        if(txqty.getText().length()==5){
            evt.consume();
        }
    }//GEN-LAST:event_txqtyKeyTyped

    private void txidPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txidPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txidPelangganActionPerformed

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new TransaksiPelanggan().setVisible(true);
            }
        });
    }
    
    public void setTanggal(){
      Date tgl = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        tanggall.setText(format.format(tgl));
    }
 
    
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    public static javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel tampilTTL;
    private javax.swing.JLabel tanggall;
    private javax.swing.JTable tbPengeluaran;
    private javax.swing.JTextField txBayar;
    public static javax.swing.JTextField txDiskon;
    public static javax.swing.JTextField txGrandTotal;
    public static javax.swing.JLabel txKasir;
    private javax.swing.JTextField txKembali;
    public static javax.swing.JTextField txNofak;
    public static javax.swing.JTextField txidPelanggan;
    public static javax.swing.JTextField txkode;
    public static javax.swing.JTextField txnama;
    public static javax.swing.JTextField txpelanggan;
    public static javax.swing.JTextField txqty;
    public static javax.swing.JTextField txtotal2;
    // End of variables declaration//GEN-END:variables
}
